### ISSUE TITLE
reset after power on 

### ISSUE THREAD

**Issue by adbensi** [pstolarz/OneWireNg#2]
Hi!

 I have one hardware that is working, and I build the Dallas example to know how this new lib work.

 But, on the load static OneWireNg *ow = new OneWireNg_CurrentPlatform(OW_PIN, false); I get reset.. on the ESP8266. Cause 1: normal boot after power-on

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
vb3acf27f
~ld 

But, if I change it to true:
static OneWireNg *ow = new OneWireNg_ArduinoESP8266(OW_PIN, true);

The issue of the reset don`t return. I Have pull UP 3K3.
This library is very robust.. I loved it! Congradulations!
Best Regards

**Comment by pstolarz** [comment]
@adbensi Thanks for the feedback. You probably found a severe bug. Will be fixed soon.

**Comment by adbensi** [comment]
Hi!
If I can do something, please tell me.. I made another sample with no block
loop and detect sensor ID too, If you like to extend samples code

Thanks a lot!!

Em qui, 20 de fev de 2020 18:13, Piotr Stolarz <notifications@github.com>
escreveu:

**Comment by pstolarz** [comment]
@adbensi @MHz000 Could you check my last commit on master with fix for the ESP8266 crash. I'd be grateful for test with and without internal pull-up resistor configured - last argument of the `OneWireNg_CurrentPlatform()` constructor set to `true` / `false`. Let me know about results...

**Comment by MHz000** [comment]
Bingo!
Chapeau, chapeau!
After changing to
static OneWireNg *ow = new OneWireNg_CurrentPlatform(OW_PIN, PWR_CTRL_PIN,
*true*);
#else
static OneWireNg *ow = new OneWireNg_CurrentPlatform(OW_PIN, *true*);
no crash any more (while set to false system crashed)
arduino serial monitor reads:
----------
28:49:49:CC:3:0:0:28 -> DS18B20
  Scratchpad: 73:1:4B:46:7F:FF:D:10:41
  Temp: 23.187 C
Congratulations!

What next? Checking the DS2438? May I ask you for an strip down example to
run the check I'll be glad to support developent of your lib. Stripped down
version means: no parsite power, no address checking, just one device on
the wire. Keep it simple as it can be makes error checking easy.
Jochen

Am Fr., 21. Feb. 2020 um 00:39 Uhr schrieb Piotr Stolarz <
notifications@github.com>:

**Comment by pstolarz** [comment]
Thanks @MHz000 but it looks like you're still working on 0.4.0 version. Could you confirm that on the latest master commit both variants work fine?

**Comment by MHz000** [comment]
downloaded from github, include .zip lib from downloads, compiling the
example
=> Error compiling for board Generic ESP8266 Module.

:-)

my fault??

Am Fr., 21. Feb. 2020 um 16:02 Uhr schrieb Piotr Stolarz <
notifications@github.com>:

**Comment by adbensi** [comment]
> @adbensi @MHz000 Could you check my last commit on master with fix for the ESP8266 crash.

@pstolarz No more reset in the false condition :)

But I no longer have the hardware to run the long test.

I will assemble a new unit exclusively for this purpose.

Some sensors, independent of the library used, work more properly when the power supply is interrupted before starting the reading continuously. I am considering this in my layout .. the point is that I have not found another way to make a sensor work if it doesn’t start on the first attemp. Then this harware fix solve theses issues.

 May be bad sensor?

 I have a lot of sensors that don´t work .. without stamp brand/model, did You hear about this?

 I'll be glad to support developent of your lib too.

 I put one file to test it..
 https://github.com/adbensi/OneWireNg/pull/1/files#diff-acd88268549e9aa747404ae7c530abcd
Best Regards!

**Comment by pstolarz** [comment]
> Some sensors, independent of the library used, work more properly when the power supply is interrupted before starting the reading continuously. I am considering this in my layout .. the point is that I have not found another way to make a sensor work if it doesn’t start on the first attemp.

Could you check my updated Dallas_Temperature example (last master commit) if it fixes the issue?

**Comment by adbensi** [comment]
Yes, I will do it, I want to understand why too.
I,ll be back :D
Thanks a lot!

Em sex., 21 de fev. de 2020 às 16:43, Piotr Stolarz <
notifications@github.com> escreveu:

**Comment by pstolarz** [comment]
I'm closing this issue, since the problem it concerns looks to be fixed. I created a new version of the library 0.4.1 with the bug fixed. Thanks guys for the report and tests.

Piotrek
