### ISSUE TITLE
CONFIG_PWR_CTRL_ENABLED with BJT instead of a MOSFET

### ISSUE THREAD

**Issue by rajiv-kanchan** [pstolarz/OneWireNg#28]
Can the circuit for `CONFIG_PWR_CTRL_ENABLED` be modified to use a BJT instead of a MOSFET? If yes how would the circuit look like?

**Comment by pstolarz** [comment]
Yes, you can use PNP bipolar transistor. More info [here](https://github.com/pstolarz/w1-gpio-cl) (as a note for `gpu` attribute). On my setups I tested both types of transistors: MOSFET and PNP and both variants worked fine.
