### ISSUE TITLE
Nano Every support

### ISSUE THREAD

**Issue by uzi18** [pstolarz/OneWireNg#54]
like https://github.com/PaulStoffregen/OneWire/issues/117
is it planed?

**Comment by pstolarz** [comment]
What's the Ardiono core for this?
Looking at the board spec., it bases on ATMega4809, which is supported by [MegaCoreX](https://github.com/MCUdude/MegaCoreX) core, therefore should work out of the box with OneWireNg. Unfortunately, I can't check it - I don't have this board.

**Comment by uzi18** [comment]
thx for the clarification.
