### ISSUE TITLE
Issue with Pi Pico

### ISSUE THREAD

**Issue by GregDuckworthRenishaw** [pstolarz/OneWireNg#58]
Hi, I have been looking to use Onewire devices with the Raspberry Pi Pico.  I have tried PaulStoffregen's library
(https://github.com/PaulStoffregen/OneWire), but I only get crashes when searching for devices.

I found your library, which seems to suggest it works with the Pico so I added the library to my PlatformIO project but I am not having much luck.

I next tried the default example in both PlatformIO and in Arduino 2.2.0 but neither library would find the device attached to the Pico.
To confirm my findings, I plugged in an Arduino Micro, using the original library, I was able to read the address of the device (therefore my pull-up is sufficient)

I can attach the project I used but it was quite literally a new Arduino IDE 2.2.0 install, automatic board manager for the board (Arduino MBED OS RP2040), only the OneWireNG library installed, and the DallasTemperature example used.  Any ideas what I can try to debug this?

Thanks

Greg

**Comment by pstolarz** [comment]
What type of error do you get? Have you set GPIO number correctly for the example?

**Comment by pstolarz** [comment]
Just checked the DallasTemperature example on my Rpi Pico setup with the following cases:
* Arduino IDE 2.2.0, core Mbed OS RP2040 v4.0.4
* Arduino IDE 2.2.0, core Rasperry Pi Pico/RP2040 by E. F. Philhower v3.4.0
* Pico SDK v1.5.1

All of them work fine, no issues observer.

**Comment by GregDuckworthRenishaw** [comment]
Thank you for the confirmation, I will go an recheck my setup and see what I can do.

Thanks

Greg

**Comment by GregDuckworthRenishaw** [comment]
Just to follow up: I have now got the DallasTemperature example working, thanks you.  

The problem I had was the level converters that the breakout board had between the Pico and the output.
More testing needed but it seems to be working well.  Thanks for the confirmation :)

Greg
