### ISSUE TITLE
esp32-s3

### ISSUE THREAD

**Issue by siwy13** [pstolarz/OneWireNg#64]
prośba o wsparcie dla esp32-s3 w bibliotece onewireng. Dzięki

**Comment by pstolarz** [comment]
S3 jest już wspierana od dość dawna. Była nawet testowana na ESP32-S3-WROOM-1.

**Comment by siwy13** [comment]
Moja pomyłka, racja wszystko ładnie działa. Dzięki za odpowiedź.
