### ISSUE TITLE
OneWireNg compatibility with WiFi.macAddress

### ISSUE THREAD

**Issue by RobertitoConti** [pstolarz/OneWireNg#65]
Hi,
I'm using ESP32 with DS18B20
When I use OneWireNg.h this one modifies my WiFi.macAddress().
Coud You Know what Im dooing wrong ?

Thanks in advance,
Roberto

**Comment by pstolarz** [comment]
I don't know what you are doing in your code but it's impossible the lib would change the MAC. It's completely unrelated to WiFi and networking. Maybe try to ask on some ESP forum.

**Comment by uzi18** [comment]
@RobertitoConti maybe there is something wrong in your code, please show it.
